remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Princeton Alg-ML Seminar
logo: /assets/img/logo.png
description: 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
